# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS workflow
on:
  push:
    branches: [ "main" ]
env:
  BUCKET_NAME : "githubsample-64537323"
  AWS_REGION : "ap-south-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::127214183072:role/aws-git-oidc
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3api put-bucket-versioning \
            --bucket "${{ env.BUCKET_NAME }}" \
            --versioning-configuration Status=Enabled \
            --region "${{ env.AWS_REGION }}"

          aws s3api put-bucket-ownership-controls \
            --bucket ${{ENV.BUCKET_NAME}} \
            --ownership-controls '{
                "Rules": [
                {
                    "ObjectOwnership": "BucketOwnerPreferred"
                }
                ]
            }'

          aws s3api get-bucket-ownership-controls --bucket ${{ENV.BUCKET_NAME}} --region ${{ env.AWS_REGION }}
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/index.html --region ${{ env.AWS_REGION }}
          aws s3 ls s3://${{ env.BUCKET_NAME }}/index.html --region ${{ env.AWS_REGION }} --acl public-read

